CC=gcc
CFLAGS=-Wall -g -DDEBUG
LDFLAGS=
LIBS=

all: 4-1 4-2 4-3-1 4-3-2 4-4 4-6 4-7 4-8 4-9 4-10 4-11 4-12 4-13 4-14 4-15 4-16 4-17 4-18 4-20 4-22 4-23 4-24 4-26 4-27 4-33 4-35 4-36 4-38 4-39

4-1: 4-1.c
	$(CC) -o $@ $(LDFLAGS) $^ $(LIBS)
4-2: 4-2.c
	$(CC) -o $@ $(LDFLAGS) $^ $(LIBS)
4-3-1: 4-3-1.c
	$(CC) -o $@ $(LDFLAGS) $^ $(LIBS)
4-3-2: 4-3-2.c
	$(CC) -o $@ $(LDFLAGS) $^ $(LIBS)
4-4: 4-4.c
	$(CC) -o $@ $(LDFLAGS) $^ $(LIBS)
4-6: 4-6-1.c 4-6-2.c
	$(CC) -o $@ $(LDFLAGS) $^ $(LIBS)
4-7: 4-7.c
	$(CC) -o $@ $(LDFLAGS) $^ $(LIBS)
4-8: 4-8.c
	$(CC) -o $@ $(LDFLAGS) $^ $(LIBS)
4-9: 4-9.c
	$(CC) -o $@ $(LDFLAGS) $^ $(LIBS)
4-10: 4-10.c
	$(CC) -o $@ $(LDFLAGS) $^ $(LIBS)
4-11: 4-11.c
	$(CC) -o $@ $(LDFLAGS) $^ $(LIBS)
4-12: 4-12.c
	$(CC) -o $@ $(LDFLAGS) $^ $(LIBS)
4-13: 4-13.c
	$(CC) -o $@ $(LDFLAGS) $^ $(LIBS)
4-14: 4-14.c
	$(CC) -o $@ $(LDFLAGS) $^ $(LIBS)
4-15: 4-15.c
	$(CC) -o $@ $(LDFLAGS) $^ $(LIBS)
4-16: 4-16.c
	$(CC) -o $@ $(LDFLAGS) $^ $(LIBS)
4-17: 4-17.c
	$(CC) -o $@ $(LDFLAGS) $^ $(LIBS)
4-18: 4-18.c
	$(CC) -o $@ $(LDFLAGS) $^ $(LIBS)
4-20: 4-20.c
	$(CC) -o $@ $(LDFLAGS) $^ $(LIBS)
4-22: 4-22.c
	$(CC) -o $@ $(LDFLAGS) $^ $(LIBS)
4-23: 4-23.c
	$(CC) -o $@ $(LDFLAGS) $^ $(LIBS)
4-24: 4-24.c
	$(CC) -o $@ $(LDFLAGS) $^ $(LIBS)
4-26: 4-26.c
	$(CC) -o $@ $(LDFLAGS) $^ $(LIBS)
4-27: 4-27.c
	$(CC) -o $@ $(LDFLAGS) $^ $(LIBS)
4-33: 4-33.c
	$(CC) -o $@ $(LDFLAGS) $^ $(LIBS)
4-35: 4-35.c
	$(CC) -o $@ $(LDFLAGS) $^ $(LIBS)
4-36: 4-36.c
	$(CC) -o $@ $(LDFLAGS) $^ $(LIBS)
4-38: 4-38.c
	$(CC) -o $@ $(LDFLAGS) $^ $(LIBS)
4-39: 4-39.c
	$(CC) -o $@ $(LDFLAGS) $^ $(LIBS)

clean:
	rm -rf *.o
