CC=gcc
CFLAGS=-Wall -g -DDEBUG
LDFLAGS=
LIBS=

all: 5-1 5-2 5-3 5-4 5-5 5-6 5-11

5-1: 5-1.c
	$(CC) -o $@ $(LDFLAGS) $^ $(LIBS)
5-2: 5-2.c
	$(CC) -o $@ $(LDFLAGS) $^ $(LIBS)
5-3: 5-3.c
	$(CC) -o $@ $(LDFLAGS) $^ $(LIBS)
5-4: 5-4.c
	$(CC) -o $@ $(LDFLAGS) $^ $(LIBS)
5-5: 5-5.c
	$(CC) -o $@ $(LDFLAGS) $^ $(LIBS)
5-6: 5-6.c
	$(CC) -o $@ $(LDFLAGS) $^ $(LIBS)
5-11: 5-11.c
	$(CC) -o $@ $(LDFLAGS) $^ $(LIBS)

clean:
	rm -rf *.o
