CC=gcc
CFLAGS=-Wall -g -DDEBUG
LDFLAGS=
LIBS=

all: 3-1 3-2 3-3 3-4 3-5 3-6 3-7

3-1: 3-1.c
	$(CC) -o $@ $(LDFLAGS) $^ $(LIBS)
3-2: 3-2.c
	$(CC) -o $@ $(LDFLAGS) $^ $(LIBS)
3-3: 3-3.c
	$(CC) -o $@ $(LDFLAGS) $^ $(LIBS)
3-4: 3-4.c
	$(CC) -o $@ $(LDFLAGS) $^ $(LIBS)
3-5: 3-5.c
	$(CC) -o $@ $(LDFLAGS) $^ $(LIBS)
3-6: 3-6.c
	$(CC) -o $@ $(LDFLAGS) $^ $(LIBS)
3-7: 3-7.c
	$(CC) -o $@ $(LDFLAGS) $^ $(LIBS)


clean:
	rm -rf *.o
