#!/bin/bash
PASSWORDFILE=$HOME/.password

function main_menu()
{
  echo
  echo
  curdate=`date "+%Y-%m-%d"`
  cat <<EOF
        DATE: $curdate
	=========================
        MENU:
           L: list
           A: appand
	   E: edit
           Q: quit
	=========================
EOF


}

function list()
#list my own password
{
   if [ -f $PASSWORDFILE ];then
      
      clear
      echo "#######################################"
         cat $PASSWORDFILE|sort
      echo "#######################################"
  else
     echo "Wrong NO File!"
   fi
}

#appand password
function appand()
{

 echo -n "Add the name: "
   read name
 echo -n "Add the password: "
   read password
 echo "${name}\$${password}">>$PASSWORDFILE

}

#edit password
function edit ()
{

  vi $PASSWORDFILE

}
#delete password
function delete()
{
echo
}

function quit()
{
  exit
}


while [ "1" == "1" ]
do
  main_menu
echo -n "Enter your answer:"

read answer
case $answer in
  l|list) list;;
  a|A)    appand;;
  E|e)    edit;;
  q|Q)    quit;;
  *)      printf "\n\n\nWrong!\n\n";;
esac

done
