CC=gcc
CFLAGS=-Wall -g -DDEBUG
LDFLAGS=
LIBS=

all: 2-1 2-2 2-3 2-4 2-5 2-6 2-7 2-8 2-9 2-10 2-11

2-1: 2-1.c
	$(CC) -o $@ $(LDFLAGS) $^ $(LIBS)
2-2: 2-2.c
	$(CC) -o $@ $(LDFLAGS) $^ $(LIBS)
2-3: 2-3.c
	$(CC) -o $@ $(LDFLAGS) $^ $(LIBS)
2-4: 2-4.c
	$(CC) -o $@ $(LDFLAGS) $^ $(LIBS)
2-5: 2-5.c
	$(CC) -o $@ $(LDFLAGS) $^ $(LIBS)
2-6: 2-6.c
	$(CC) -o $@ $(LDFLAGS) $^ $(LIBS)
2-7: 2-7.c
	$(CC) -o $@ $(LDFLAGS) $^ $(LIBS)
2-8: 2-8.c
	$(CC) -o $@ $(LDFLAGS) $^ $(LIBS)
2-9: 2-9.c
	$(CC) -o $@ $(LDFLAGS) $^ $(LIBS)
2-10: 2-10.c
	$(CC) -o $@ $(LDFLAGS) $^ $(LIBS)
2-11: 2-11.c
	$(CC) -o $@ $(LDFLAGS) $^ $(LIBS)

clean:
	rm -rf *.o
